# Generated by Django 4.2.2 on 2023-07-01 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_key_is_rsa_alter_user_last_pull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='server.user'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.BinaryField()),
                ('recipient_key_id', models.BinaryField(db_index=True, unique=True)),
                ('sender_dh_public_key', models.BinaryField()),
                ('sender_rsa_key_id', models.BinaryField()),
                ('key_id', models.BinaryField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='server.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='server.user')),
            ],
        ),
    ]
