# Generated by Django 4.2.2 on 2023-07-01 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_key_user_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='sender_rsa_key_id',
            new_name='sender_rsa_public_key',
        ),
    ]
