# Generated by Django 4.2.2 on 2023-07-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_rename_sender_rsa_key_id_chatmessage_sender_rsa_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='recipient_key_id',
            field=models.BinaryField(),
        ),
    ]
