# Generated by Django 4.2.2 on 2023-07-01 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.group'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='recipient_key_id',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='GroupMessage',
        ),
    ]
